### ISSUE TITLE
USER STORY: Navigation bar

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#1]
As a **user** I can **navigate through pages quickly** so that I can **view content seamlessly without page refresh**

##  Acceptance Criteria

- Nav bar displays at the top of all pages
- Update nav view based on login status
- All links work and take the user to the correct url
- Hamburger menu present and working on small screen sizes 

## Tasks
 - [x] Create links for logged in and logged out users
 - [x] Make accessible across pages
 - [x] Ensure hamburger menu displays for smaller screen sizes
