### ISSUE TITLE
USER STORY: Delete a Post

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#11]
As a **user** I can **delete a Post** so that **I can remove it from the platform**

## Acceptance Criteria
 - Users can click into their own walk posts and access a 'delete' button from a dropdown menu so that they can delete the post

## Tasks
- [x] Add the button  allow post owners to choose to delete a post
- [x] Allow the API request to remove the selected post from the results array
- [x] Handle routing to redirect the user to the posts page upon completion
