### ISSUE TITLE
USER STORY: Like a Post 

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#12]
As a **logged in user** I can **like a post so that I can show my support for the posts that interest me**

## Acceptance Criteria
- Clickable like button that will allow users to like/unlike with the click of a button

## Tasks:
 - [x] Create the like/unlike button
 - [x] Write the post request so that the API knows which post the user is trying to like
 - [x] Implement the logic for incrementing/decrementing the likes count
