### ISSUE TITLE
USER STORY: Edit Comment

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#15]
As an **owner of a comment** I can **edit my comment** so that **I can correct/update it**

## Acceptance Criteria
- The user can click 'edit' and update the comment

## Tasks:
 - [x] Create a dropdown menu to give users the options to edit their own comments
- [x] Create and style form to edit a comment
- [x] Populate the form with existing content
- [x] Write the API request to save updated the content to the database
