### ISSUE TITLE
USER STORY: Delete Comment

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#16]
As an **owner of a comment** I can **delete my comment from the post** so that **I remove it from a certain Post**

## Acceptance Criteria
 The user can click 'delete'  to remove his comment from the post

## Tasks:
 - [x] Create a dropdown menu to give users the options to delete their own comments
 - [x] Implement the logic to remove the selected comment from the state (update results array)
 - [x] Rout user back to post page
