### ISSUE TITLE
USER STORY: Search Posts

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#17]
As a **user** **I can search for posts using keywords**  so that **I can find the ones I am interested in**

## Acceptance Criteria
 - Search bar is available on all pages
 - Search bar returns results filtered by keywords

## Tasks:
- [x] Add and style the search bar
- [x] Filter results by relevant data
- [x] Display results searched by users
