### ISSUE TITLE
USER STORY: Read Profile Page

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#19]
As a **user** I can **view the profile page** so that **I can see more information about a given user**

## Acceptance Criteria
- generate page that populates with profile data

## Tasks:
 - [x] Build view page for profile details
 - [x] Make username and avatar clickable to generate new view
 - [x] Populate page with selected user data
