### ISSUE TITLE
USER STORY: Authentication - Sign up

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#2]
As a **user** I can **sign up for a new account** so that I can **access all the features available for signed up users**

## Acceptance Criteria
- Link to Sign Up form present in navbar
- Once a user is signed up, they are re-directed to the home page
- A user account/profile is created in the DRF API

## Tasks
- [x] Add Sign Up link to nav bar
- [x] Create Sign Up form
- [x] Re-route to sign in page
- [x] Ensure sign up data is posted to the API
