### ISSUE TITLE
USER STORY: Edit Profile 

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#20]
As a **logged in user** I can **edit my profile** so that **I can change my profile picture, information about me, username and password**

## Acceptance Criteria
 - A dropdown menu is available to a user on their profile so that they can edit their own details.
 
## Tasks:
- [x] Add a dropdown menu for users to edit their profile
- [x] Create the form to edit the profile's username
- [x] Create the form to update the profile's password
- [x]  Populate the forms with the existing data
- [x] Save the new form data to the database
- [x] Handle routing to redirect the user to the profile page
