### ISSUE TITLE
USER STORY: Follow/Unfollow Feed

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#21]
As a **user** I can **follow or unfollow** a user **so that I can see their  posts easily**

## Acceptance Criteria:
- Users can click the Follow/Unfollow button on another user's profile to stay up to date with that user's activity on the platform
 - Following feed displays posts filtered by profiles the user is following
 - 
## Tasks:
- [x] Follow / unfollow button
- [x] Update button to reflect follow status
 - [x] Ensure only posts filtered by profiles the user is following are shown in this feed
