### ISSUE TITLE
USER STORY: Post category 

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#23]
As a **user** I can **view a category for the post** so that **I know which theme the content relates to**.

Acceptance Criteria
- Panel with buttons indicating different categories of posts
- Display the filtered results

## Tasks:
- [x] Add the category field to Create and Edit Post
- [x] Add and style the category buttons
- [x] Filter results by category
