### ISSUE TITLE
USER STORY: View Workshops

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#25]
As a **user** I can **view all workshops on the home page** so that **I can quickly be informed**.

## Acceptance Criteria
- latest workshops visible on the home page

## Tasks
- [x] populate workshops page with all shared workshops
- [x] display workshops in chronological order, newest first
- [x] incorporate infinite scroll
