### ISSUE TITLE
USER STORY: Delete Workshop

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#28]
As a **workshop owner** I can **delete it** so that **I can remove it from the platform**

## Acceptance Criteria
 - Users can click into their own workshops and access a 'delete' button from a dropdown menu so that they can delete the post

## Tasks
- [x] Add the button  allow post owners to choose to delete a workshop
- [x] Allow the API request to remove the selected workshop from the results array
- [x] Handle routing to redirect the user to the workshops page upon completion
