### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#29]
As a **user** I can **fill out and submit a contact form** so that **I can make admin aware of any issues or feedback**

## Acceptance Criteria
- Link to contact form is available in navigation bar
- Form can be filled in and submitted
- Form is accessible in admin area of DRF

## Tasks
- [x] Create contact form
- [x] Add link to Contact Us form in navigation bar
- [x] Add re-direct to confirmation page upon successful submission of form
