### ISSUE TITLE
USER STORY: Authentication - Sign in

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#3]
As a **user** I can **log in with my credentials** so that I **can access all features available to signed up users**

## Acceptance Criteria
 - The link to Log In form present in the navigation bar
 - The functionality is available to logged in user
 - Navigation layout updates upon login

## Tasks
- [x] Add Log in link to nav bar
- [x] Create form for username and password
- [x] Re-route back to previous page
