### ISSUE TITLE
USER STORY : Post details

### ISSUE THREAD

**Issue by ANaRobe** [ANaRobe/portfolio-five-frontend#9]
As a **user**, I can **view the details of a single post** so that **I read the whole information  and other users comments & likes**

## Acceptance Criteria
- Users can click into a walk post and view all information
 - Users can read a walk post's comment list and access the comment form within the walk post page

## Tasks
- [x] Create a detail post page
- [x] Add like icon
- [x] Add comment form
